name: Node CI

on: [push,pull_request,release]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x,12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install babel
      run: npm -g install babel-cli
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm test
      env:
        CI: true
    - name: Run babel
      run: babel ./ -d ./bin --minified --ignore 'node_modules/'
  build:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
        arch:
          - amd64
          - armhf
          - arm64
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install babel
      run: npm -g install babel-cli
    - name: Install qemu
      run: |
        sudo apt-get update
        sudo apt-get -y install qemu qemu-user-static
        docker run --rm --privileged multiarch/qemu-user-static:register
        if [[ "$ARCH" == "amd64" ]]; then export export QEMU_ARCH=x86_64; fi
        if [[ "$ARCH" == "armhf" ]]; then export export QEMU_ARCH=arm; fi
        if [[ "$ARCH" == "arm64" ]]; then export export QEMU_ARCH=aarch64; fi
        wget https://github.com/multiarch/qemu-user-static/releases/download/$QEMU_VER/x86_64_qemu-${QEMU_ARCH}-static.tar.gz
        tar -xvf x86_64_qemu-${QEMU_ARCH}-static.tar.gz;
      env:
        QEMU_VER: v4.1.0-1
        ARCH: ${{ matrix.arch }}
    - name: npm install
      run: npm install
    - name: Run babel
      run: babel ./ -d ./bin --minified --ignore 'node_modules/'
    - name: Build the Docker image
      run: |
        rm -fr node_modules
        if [[ "$ARCH" == "amd64" ]]; then export ARCHREPO=amd64; export QEMU_ARCH=x86_64; fi
        if [[ "$ARCH" == "armhf" ]]; then export ARCHREPO=arm32v7; export QEMU_ARCH=arm; fi
        if [[ "$ARCH" == "arm64" ]]; then export ARCHREPO=arm64v8; export QEMU_ARCH=aarch64; fi
        docker build . --build-arg="ARCH=$ARCH" --build-arg="ARCHREPO=$ARCHREPO" --build-arg "QEMU_ARCH=$QEMU_ARCH" --file Dockerfile --tag docker.pkg.github.com/innovate-technologies/cast/$ARCH:latest
      env:
        ARCH: ${{ matrix.arch }}
    - name: Docker login
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin "${{ secrets.REGISTRY_URL }}"
    - name: Docker push master
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: |
        docker tag docker.pkg.github.com/innovate-technologies/cast/$ARCH:latest innovate/cast:$ARCH-master
        docker tag docker.pkg.github.com/innovate-technologies/cast/$ARCH:latest innovate/cast:$ARCH-$GITHUB_SHA
        docker push innovate/cast:$ARCH-master
        docker push innovate/cast:$ARCH-$GITHUB_SHA
        docker push "${{ secrets.REGISTRY_URL }}"/cast:$ARCH-stable
      env:
        ARCH: ${{ matrix.arch }}
    - name: Docker push tag
      if: github.event_name == 'release'
      run: |
        docker tag docker.pkg.github.com/innovate-technologies/cast/$ARCH:latest innovate/cast:$ARCH-$GITHUB_REF
        docker push innovate/cast:$ARCH-$GITHUB_REF
      env:
        ARCH: ${{ matrix.arch }}
